import os
import requests
import json

from dotenv import load_dotenv
load_dotenv()


class WMATA:

    def __init__(self):
        self.base_url = "https://api.wmata.com"
        self.headers = {
            "api_key": os.environ.get("WMATA_KEY")
        }
        self.line_colors = {
            "RD": "#be1337",
            "BL": "#0795d3",
            "OR": "#da8707",
            "YL": "#f5d415",
            "GR": "#00b050",
            "SV": "#a2a4a1",
        }

    def _fetch(self, endpoint, params=None):
        target = f"{self.base_url}{endpoint}"

        response = requests.get(target, headers=self.headers, params=params)
        try:
            return json.loads(response.text)
        except:  # as no data is set, an exception will be raised later in the method
            raise Exception("error bruh")

    def fetch_station_definitions(self, line_code: str = None, latlong_range: int = 1000):

        data = self._fetch("/Rail.svc/json/jStations", params={"LineCode": line_code})

        max_lat = max([station["Lat"] for station in data["Stations"]])
        max_lon = max([station["Lon"] for station in data["Stations"]])
        min_lat = min([station["Lat"] for station in data["Stations"]])
        min_lon = min([station["Lon"] for station in data["Stations"]])

        for station in data["Stations"]:
            station["Lat"] = round((station["Lat"] - min_lat) / (max_lat - min_lat) * latlong_range)
            station["Lon"] = round((station["Lon"] - min_lon) / (max_lon - min_lon) * latlong_range)
            station["ColorHex"] = self.line_colors.get(station["LineCode1"])

        data["MaxHeight"] = max([station["Lat"] for station in data["Stations"]])
        # buffer space for edge station
        data["MaxWidth"] = max([station["Lon"] for station in data["Stations"]]) + 10

        return data

    def fetch_circuits(self):
        data = self._fetch("/TrainPositions/StandardRoutes?contentType=json")
        
        for route in data["StandardRoutes"]:
            route["LineColor"] = self.line_colors.get(route["LineCode"])

        return data
        # return {
        #     "StandardRoutes": [{
        #         "LineCode": "BL",
        #         "LineColor": self.line_colors.get("BL"),
        #         "TrackNum": 1,
        #         "TrackCircuits": [
        #             {
        #                 "SeqNum": 0,
        #                 "CircuitId": 2603,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 1,
        #                 "CircuitId": 2604,
        #                 "StationCode": "J03"
        #             }, {
        #                 "SeqNum": 2,
        #                 "CircuitId": 2605,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 3,
        #                 "CircuitId": 2606,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 4,
        #                 "CircuitId": 2607,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 5,
        #                 "CircuitId": 2608,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 6,
        #                 "CircuitId": 2609,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 7,
        #                 "CircuitId": 2610,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 8,
        #                 "CircuitId": 2611,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 9,
        #                 "CircuitId": 2612,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 10,
        #                 "CircuitId": 2613,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 11,
        #                 "CircuitId": 2614,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 12,
        #                 "CircuitId": 2615,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 13,
        #                 "CircuitId": 2616,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 14,
        #                 "CircuitId": 2617,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 15,
        #                 "CircuitId": 2618,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 16,
        #                 "CircuitId": 2619,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 17,
        #                 "CircuitId": 2620,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 18,
        #                 "CircuitId": 2621,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 19,
        #                 "CircuitId": 2622,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 20,
        #                 "CircuitId": 2623,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 21,
        #                 "CircuitId": 2624,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 22,
        #                 "CircuitId": 2625,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 23,
        #                 "CircuitId": 2626,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 24,
        #                 "CircuitId": 2627,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 25,
        #                 "CircuitId": 2628,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 26,
        #                 "CircuitId": 2629,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 27,
        #                 "CircuitId": 2630,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 28,
        #                 "CircuitId": 2631,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 29,
        #                 "CircuitId": 2632,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 30,
        #                 "CircuitId": 2633,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 31,
        #                 "CircuitId": 2634,
        #                 "StationCode": "J02"
        #             }, {
        #                 "SeqNum": 32,
        #                 "CircuitId": 2635,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 33,
        #                 "CircuitId": 2636,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 34,
        #                 "CircuitId": 2637,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 35,
        #                 "CircuitId": 2638,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 36,
        #                 "CircuitId": 2639,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 37,
        #                 "CircuitId": 2640,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 38,
        #                 "CircuitId": 2641,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 39,
        #                 "CircuitId": 2642,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 40,
        #                 "CircuitId": 2643,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 41,
        #                 "CircuitId": 2644,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 42,
        #                 "CircuitId": 2645,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 43,
        #                 "CircuitId": 2646,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 44,
        #                 "CircuitId": 2647,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 45,
        #                 "CircuitId": 2648,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 46,
        #                 "CircuitId": 2649,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 47,
        #                 "CircuitId": 2650,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 48,
        #                 "CircuitId": 2651,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 49,
        #                 "CircuitId": 2652,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 50,
        #                 "CircuitId": 2653,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 51,
        #                 "CircuitId": 2654,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 52,
        #                 "CircuitId": 2655,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 53,
        #                 "CircuitId": 2656,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 54,
        #                 "CircuitId": 2657,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 55,
        #                 "CircuitId": 2658,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 56,
        #                 "CircuitId": 2659,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 57,
        #                 "CircuitId": 2660,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 58,
        #                 "CircuitId": 2661,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 59,
        #                 "CircuitId": 2662,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 60,
        #                 "CircuitId": 2663,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 61,
        #                 "CircuitId": 2664,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 62,
        #                 "CircuitId": 2665,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 63,
        #                 "CircuitId": 2666,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 64,
        #                 "CircuitId": 2667,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 65,
        #                 "CircuitId": 2668,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 66,
        #                 "CircuitId": 2669,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 67,
        #                 "CircuitId": 2670,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 68,
        #                 "CircuitId": 2671,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 69,
        #                 "CircuitId": 2672,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 70,
        #                 "CircuitId": 2673,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 71,
        #                 "CircuitId": 966,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 72,
        #                 "CircuitId": 967,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 73,
        #                 "CircuitId": 968,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 74,
        #                 "CircuitId": 969,
        #                 "StationCode": "C13"
        #             }, {
        #                 "SeqNum": 75,
        #                 "CircuitId": 970,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 76,
        #                 "CircuitId": 971,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 77,
        #                 "CircuitId": 972,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 78,
        #                 "CircuitId": 973,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 79,
        #                 "CircuitId": 974,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 80,
        #                 "CircuitId": 975,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 81,
        #                 "CircuitId": 976,
        #                 "StationCode": "C12"
        #             }, {
        #                 "SeqNum": 82,
        #                 "CircuitId": 977,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 83,
        #                 "CircuitId": 978,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 84,
        #                 "CircuitId": 979,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 85,
        #                 "CircuitId": 980,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 86,
        #                 "CircuitId": 981,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 87,
        #                 "CircuitId": 982,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 88,
        #                 "CircuitId": 983,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 89,
        #                 "CircuitId": 984,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 90,
        #                 "CircuitId": 985,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 91,
        #                 "CircuitId": 986,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 92,
        #                 "CircuitId": 987,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 93,
        #                 "CircuitId": 988,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 94,
        #                 "CircuitId": 989,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 95,
        #                 "CircuitId": 990,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 96,
        #                 "CircuitId": 991,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 97,
        #                 "CircuitId": 992,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 98,
        #                 "CircuitId": 993,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 99,
        #                 "CircuitId": 994,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 100,
        #                 "CircuitId": 995,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 101,
        #                 "CircuitId": 996,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 102,
        #                 "CircuitId": 997,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 103,
        #                 "CircuitId": 998,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 104,
        #                 "CircuitId": 999,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 105,
        #                 "CircuitId": 1000,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 106,
        #                 "CircuitId": 1001,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 107,
        #                 "CircuitId": 1002,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 108,
        #                 "CircuitId": 1003,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 109,
        #                 "CircuitId": 1004,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 110,
        #                 "CircuitId": 1005,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 111,
        #                 "CircuitId": 1006,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 112,
        #                 "CircuitId": 1007,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 113,
        #                 "CircuitId": 1008,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 114,
        #                 "CircuitId": 1009,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 115,
        #                 "CircuitId": 1010,
        #                 "StationCode": "C10"
        #             }, {
        #                 "SeqNum": 116,
        #                 "CircuitId": 1011,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 117,
        #                 "CircuitId": 1012,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 118,
        #                 "CircuitId": 1013,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 119,
        #                 "CircuitId": 1014,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 120,
        #                 "CircuitId": 1015,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 121,
        #                 "CircuitId": 1016,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 122,
        #                 "CircuitId": 1017,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 123,
        #                 "CircuitId": 1018,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 124,
        #                 "CircuitId": 1019,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 125,
        #                 "CircuitId": 1020,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 126,
        #                 "CircuitId": 1021,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 127,
        #                 "CircuitId": 1022,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 128,
        #                 "CircuitId": 1023,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 129,
        #                 "CircuitId": 1024,
        #                 "StationCode": "C09"
        #             }, {
        #                 "SeqNum": 130,
        #                 "CircuitId": 1025,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 131,
        #                 "CircuitId": 1026,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 132,
        #                 "CircuitId": 1027,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 133,
        #                 "CircuitId": 1028,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 134,
        #                 "CircuitId": 1029,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 135,
        #                 "CircuitId": 1030,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 136,
        #                 "CircuitId": 1031,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 137,
        #                 "CircuitId": 1032,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 138,
        #                 "CircuitId": 1033,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 139,
        #                 "CircuitId": 1034,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 140,
        #                 "CircuitId": 1035,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 141,
        #                 "CircuitId": 1036,
        #                 "StationCode": "C08"
        #             }, {
        #                 "SeqNum": 142,
        #                 "CircuitId": 1037,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 143,
        #                 "CircuitId": 1038,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 144,
        #                 "CircuitId": 1039,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 145,
        #                 "CircuitId": 1040,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 146,
        #                 "CircuitId": 1041,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 147,
        #                 "CircuitId": 1042,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 148,
        #                 "CircuitId": 1043,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 149,
        #                 "CircuitId": 1044,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 150,
        #                 "CircuitId": 1045,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 151,
        #                 "CircuitId": 1046,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 152,
        #                 "CircuitId": 1047,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 153,
        #                 "CircuitId": 1048,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 154,
        #                 "CircuitId": 1049,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 155,
        #                 "CircuitId": 1050,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 156,
        #                 "CircuitId": 1051,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 157,
        #                 "CircuitId": 1052,
        #                 "StationCode": "C07"
        #             }, {
        #                 "SeqNum": 158,
        #                 "CircuitId": 1053,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 159,
        #                 "CircuitId": 1054,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 160,
        #                 "CircuitId": 1055,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 161,
        #                 "CircuitId": 1056,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 162,
        #                 "CircuitId": 1057,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 163,
        #                 "CircuitId": 1058,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 164,
        #                 "CircuitId": 1059,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 165,
        #                 "CircuitId": 1060,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 166,
        #                 "CircuitId": 1061,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 167,
        #                 "CircuitId": 1062,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 168,
        #                 "CircuitId": 1063,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 169,
        #                 "CircuitId": 1064,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 170,
        #                 "CircuitId": 1065,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 171,
        #                 "CircuitId": 1066,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 172,
        #                 "CircuitId": 1067,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 173,
        #                 "CircuitId": 1068,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 174,
        #                 "CircuitId": 1069,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 175,
        #                 "CircuitId": 1070,
        #                 "StationCode": "C06"
        #             }, {
        #                 "SeqNum": 176,
        #                 "CircuitId": 1071,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 177,
        #                 "CircuitId": 1072,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 178,
        #                 "CircuitId": 1073,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 179,
        #                 "CircuitId": 1074,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 180,
        #                 "CircuitId": 1075,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 181,
        #                 "CircuitId": 1076,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 182,
        #                 "CircuitId": 1077,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 183,
        #                 "CircuitId": 1078,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 184,
        #                 "CircuitId": 1079,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 185,
        #                 "CircuitId": 1080,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 186,
        #                 "CircuitId": 1081,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 187,
        #                 "CircuitId": 1082,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 188,
        #                 "CircuitId": 1083,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 189,
        #                 "CircuitId": 1084,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 190,
        #                 "CircuitId": 1085,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 191,
        #                 "CircuitId": 1086,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 192,
        #                 "CircuitId": 1087,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 193,
        #                 "CircuitId": 1088,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 194,
        #                 "CircuitId": 1089,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 195,
        #                 "CircuitId": 1090,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 196,
        #                 "CircuitId": 1091,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 197,
        #                 "CircuitId": 1092,
        #                 "StationCode": "C05"
        #             }, {
        #                 "SeqNum": 198,
        #                 "CircuitId": 1093,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 199,
        #                 "CircuitId": 1094,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 200,
        #                 "CircuitId": 1095,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 201,
        #                 "CircuitId": 1096,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 202,
        #                 "CircuitId": 1097,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 203,
        #                 "CircuitId": 1098,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 204,
        #                 "CircuitId": 1099,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 205,
        #                 "CircuitId": 1100,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 206,
        #                 "CircuitId": 1101,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 207,
        #                 "CircuitId": 1102,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 208,
        #                 "CircuitId": 1103,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 209,
        #                 "CircuitId": 1104,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 210,
        #                 "CircuitId": 1105,
        #                 "StationCode": "C04"
        #             }, {
        #                 "SeqNum": 211,
        #                 "CircuitId": 1106,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 212,
        #                 "CircuitId": 1107,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 213,
        #                 "CircuitId": 1108,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 214,
        #                 "CircuitId": 1109,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 215,
        #                 "CircuitId": 1110,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 216,
        #                 "CircuitId": 1111,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 217,
        #                 "CircuitId": 1112,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 218,
        #                 "CircuitId": 1113,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 219,
        #                 "CircuitId": 1114,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 220,
        #                 "CircuitId": 1115,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 221,
        #                 "CircuitId": 1116,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 222,
        #                 "CircuitId": 1117,
        #                 "StationCode": "C03"
        #             }, {
        #                 "SeqNum": 223,
        #                 "CircuitId": 1118,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 224,
        #                 "CircuitId": 1119,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 225,
        #                 "CircuitId": 1120,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 226,
        #                 "CircuitId": 1121,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 227,
        #                 "CircuitId": 1122,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 228,
        #                 "CircuitId": 1123,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 229,
        #                 "CircuitId": 1124,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 230,
        #                 "CircuitId": 1125,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 231,
        #                 "CircuitId": 1126,
        #                 "StationCode": "C02"
        #             }, {
        #                 "SeqNum": 232,
        #                 "CircuitId": 1127,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 233,
        #                 "CircuitId": 1128,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 234,
        #                 "CircuitId": 1129,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 235,
        #                 "CircuitId": 1130,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 236,
        #                 "CircuitId": 1131,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 237,
        #                 "CircuitId": 1132,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 238,
        #                 "CircuitId": 1133,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 239,
        #                 "CircuitId": 1134,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 240,
        #                 "CircuitId": 1135,
        #                 "StationCode": "C01"
        #             }, {
        #                 "SeqNum": 241,
        #                 "CircuitId": 1378,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 242,
        #                 "CircuitId": 1379,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 243,
        #                 "CircuitId": 1380,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 244,
        #                 "CircuitId": 1381,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 245,
        #                 "CircuitId": 1382,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 246,
        #                 "CircuitId": 1383,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 247,
        #                 "CircuitId": 1384,
        #                 "StationCode": "D01"
        #             }, {
        #                 "SeqNum": 248,
        #                 "CircuitId": 1385,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 249,
        #                 "CircuitId": 1386,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 250,
        #                 "CircuitId": 1387,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 251,
        #                 "CircuitId": 1388,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 252,
        #                 "CircuitId": 1389,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 253,
        #                 "CircuitId": 1390,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 254,
        #                 "CircuitId": 1391,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 255,
        #                 "CircuitId": 1392,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 256,
        #                 "CircuitId": 1393,
        #                 "StationCode": "D02"
        #             }, {
        #                 "SeqNum": 257,
        #                 "CircuitId": 1394,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 258,
        #                 "CircuitId": 1395,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 259,
        #                 "CircuitId": 1396,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 260,
        #                 "CircuitId": 1397,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 261,
        #                 "CircuitId": 1398,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 262,
        #                 "CircuitId": 1399,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 263,
        #                 "CircuitId": 1400,
        #                 "StationCode": "D03"
        #             }, {
        #                 "SeqNum": 264,
        #                 "CircuitId": 1401,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 265,
        #                 "CircuitId": 1402,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 266,
        #                 "CircuitId": 1403,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 267,
        #                 "CircuitId": 1404,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 268,
        #                 "CircuitId": 1405,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 269,
        #                 "CircuitId": 1406,
        #                 "StationCode": "D04"
        #             }, {
        #                 "SeqNum": 270,
        #                 "CircuitId": 1407,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 271,
        #                 "CircuitId": 1408,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 272,
        #                 "CircuitId": 1409,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 273,
        #                 "CircuitId": 1410,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 274,
        #                 "CircuitId": 1411,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 275,
        #                 "CircuitId": 1412,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 276,
        #                 "CircuitId": 1413,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 277,
        #                 "CircuitId": 1414,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 278,
        #                 "CircuitId": 1415,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 279,
        #                 "CircuitId": 1416,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 280,
        #                 "CircuitId": 1417,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 281,
        #                 "CircuitId": 1418,
        #                 "StationCode": "D05"
        #             }, {
        #                 "SeqNum": 282,
        #                 "CircuitId": 1419,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 283,
        #                 "CircuitId": 1420,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 284,
        #                 "CircuitId": 1421,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 285,
        #                 "CircuitId": 1422,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 286,
        #                 "CircuitId": 1423,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 287,
        #                 "CircuitId": 1424,
        #                 "StationCode": "D06"
        #             }, {
        #                 "SeqNum": 288,
        #                 "CircuitId": 1425,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 289,
        #                 "CircuitId": 1426,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 290,
        #                 "CircuitId": 1427,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 291,
        #                 "CircuitId": 1428,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 292,
        #                 "CircuitId": 1429,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 293,
        #                 "CircuitId": 1430,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 294,
        #                 "CircuitId": 1431,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 295,
        #                 "CircuitId": 1432,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 296,
        #                 "CircuitId": 1433,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 297,
        #                 "CircuitId": 1434,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 298,
        #                 "CircuitId": 1435,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 299,
        #                 "CircuitId": 1436,
        #                 "StationCode": "D07"
        #             }, {
        #                 "SeqNum": 300,
        #                 "CircuitId": 1437,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 301,
        #                 "CircuitId": 1438,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 302,
        #                 "CircuitId": 1439,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 303,
        #                 "CircuitId": 1440,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 304,
        #                 "CircuitId": 1441,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 305,
        #                 "CircuitId": 1442,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 306,
        #                 "CircuitId": 1443,
        #                 "StationCode": "D08"
        #             }, {
        #                 "SeqNum": 307,
        #                 "CircuitId": 1444,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 308,
        #                 "CircuitId": 1445,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 309,
        #                 "CircuitId": 1446,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 310,
        #                 "CircuitId": 1447,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 311,
        #                 "CircuitId": 1448,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 312,
        #                 "CircuitId": 1449,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 313,
        #                 "CircuitId": 1450,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 314,
        #                 "CircuitId": 1451,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 315,
        #                 "CircuitId": 1452,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 316,
        #                 "CircuitId": 1453,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 317,
        #                 "CircuitId": 1454,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 318,
        #                 "CircuitId": 1455,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 319,
        #                 "CircuitId": 1456,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 320,
        #                 "CircuitId": 1457,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 321,
        #                 "CircuitId": 1458,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 322,
        #                 "CircuitId": 1459,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 323,
        #                 "CircuitId": 1460,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 324,
        #                 "CircuitId": 1461,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 325,
        #                 "CircuitId": 2409,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 326,
        #                 "CircuitId": 2410,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 327,
        #                 "CircuitId": 2411,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 328,
        #                 "CircuitId": 2412,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 329,
        #                 "CircuitId": 2413,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 330,
        #                 "CircuitId": 2414,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 331,
        #                 "CircuitId": 2415,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 332,
        #                 "CircuitId": 2416,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 333,
        #                 "CircuitId": 2417,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 334,
        #                 "CircuitId": 2418,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 335,
        #                 "CircuitId": 2419,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 336,
        #                 "CircuitId": 2420,
        #                 "StationCode": "G01"
        #             }, {
        #                 "SeqNum": 337,
        #                 "CircuitId": 2421,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 338,
        #                 "CircuitId": 2422,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 339,
        #                 "CircuitId": 2423,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 340,
        #                 "CircuitId": 2424,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 341,
        #                 "CircuitId": 2425,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 342,
        #                 "CircuitId": 2426,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 343,
        #                 "CircuitId": 2427,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 344,
        #                 "CircuitId": 2428,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 345,
        #                 "CircuitId": 2429,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 346,
        #                 "CircuitId": 2430,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 347,
        #                 "CircuitId": 2431,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 348,
        #                 "CircuitId": 2432,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 349,
        #                 "CircuitId": 2433,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 350,
        #                 "CircuitId": 2434,
        #                 "StationCode": "G02"
        #             }, {
        #                 "SeqNum": 351,
        #                 "CircuitId": 2435,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 352,
        #                 "CircuitId": 2436,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 353,
        #                 "CircuitId": 2437,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 354,
        #                 "CircuitId": 2438,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 355,
        #                 "CircuitId": 2439,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 356,
        #                 "CircuitId": 2440,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 357,
        #                 "CircuitId": 2441,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 358,
        #                 "CircuitId": 2442,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 359,
        #                 "CircuitId": 2443,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 360,
        #                 "CircuitId": 2444,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 361,
        #                 "CircuitId": 2445,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 362,
        #                 "CircuitId": 2446,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 363,
        #                 "CircuitId": 2447,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 364,
        #                 "CircuitId": 2448,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 365,
        #                 "CircuitId": 2449,
        #                 "StationCode": "G03"
        #             }, {
        #                 "SeqNum": 366,
        #                 "CircuitId": 2450,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 367,
        #                 "CircuitId": 2451,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 368,
        #                 "CircuitId": 2452,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 369,
        #                 "CircuitId": 2453,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 370,
        #                 "CircuitId": 2454,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 371,
        #                 "CircuitId": 2455,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 372,
        #                 "CircuitId": 2456,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 373,
        #                 "CircuitId": 2457,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 374,
        #                 "CircuitId": 2458,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 375,
        #                 "CircuitId": 2459,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 376,
        #                 "CircuitId": 2460,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 377,
        #                 "CircuitId": 2461,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 378,
        #                 "CircuitId": 2462,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 379,
        #                 "CircuitId": 2463,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 380,
        #                 "CircuitId": 2464,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 381,
        #                 "CircuitId": 2465,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 382,
        #                 "CircuitId": 2466,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 383,
        #                 "CircuitId": 2467,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 384,
        #                 "CircuitId": 2468,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 385,
        #                 "CircuitId": 2469,
        #                 "StationCode": "G04"
        #             }, {
        #                 "SeqNum": 386,
        #                 "CircuitId": 2470,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 387,
        #                 "CircuitId": 2471,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 388,
        #                 "CircuitId": 2472,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 389,
        #                 "CircuitId": 2473,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 390,
        #                 "CircuitId": 2474,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 391,
        #                 "CircuitId": 2475,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 392,
        #                 "CircuitId": 2476,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 393,
        #                 "CircuitId": 2477,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 394,
        #                 "CircuitId": 2478,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 395,
        #                 "CircuitId": 2479,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 396,
        #                 "CircuitId": 2480,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 397,
        #                 "CircuitId": 2481,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 398,
        #                 "CircuitId": 2482,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 399,
        #                 "CircuitId": 2483,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 400,
        #                 "CircuitId": 2484,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 401,
        #                 "CircuitId": 2485,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 402,
        #                 "CircuitId": 2486,
        #                 "StationCode": None
        #             }, {
        #                 "SeqNum": 403,
        #                 "CircuitId": 2487,
        #                 "StationCode": "G05"
        #             }, {
        #                 "SeqNum": 404,
        #                 "CircuitId": 2488,
        #                 "StationCode": None
        #             }
        #         ]
        #     }
        # ]}
